"""baseline

Revision ID: bcbad57cb74f
Revises:
Create Date: 2026-04-11 01:47:25.380699

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "bcbad57cb74f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
